# Generated by Django 3.2.25 on 2024-12-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('check_in_date', models.DateTimeField(blank=True, null=True)),
                ('check_out_date', models.DateTimeField(blank=True, null=True)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('environment_temperature', models.IntegerField()),
                ('current_temperature', models.DecimalField(decimal_places=2, default=26.0, max_digits=5)),
                ('power', models.BooleanField(default=False)),
                ('ac_usage_time', models.IntegerField(default=0)),
                ('ac_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_card', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.room')),
            ],
        ),
        migrations.CreateModel(
            name='AirConditioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, default=26.0, max_digits=5)),
                ('mode', models.CharField(choices=[('cool', 'Cool'), ('heat', 'Heat')], default='cool', max_length=10)),
                ('speed', models.IntegerField(default=2)),
                ('queue', models.CharField(choices=[('服务中', '服务中'), ('等待中', '等待中')], default='等待中', max_length=10)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='air_conditioner', to='testapp.room')),
            ],
        ),
    ]
