# Generated by Django 3.2.25 on 2024-12-13 14:55

from django.db import migrations

def delete_all_data(apps, schema_editor):
    Room = apps.get_model('testapp', 'Room')
    Customer = apps.get_model('testapp', 'Customer')
    AirConditioner = apps.get_model('testapp', 'AirConditioner')

    Room.objects.all().delete()
    Customer.objects.all().delete()
    AirConditioner.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),  # Adjust this to your actual initial migration file
    ]

    operations = [
        migrations.RunPython(delete_all_data),
    ]
