# Generated by Django 3.2.25 on 2024-12-13 14:55

from django.db import migrations

def add_new_rooms(apps, schema_editor):
    Room = apps.get_model('testapp', 'Room')
    rooms_to_add = [
        Room(room_number='房间一', is_occupied=False, total_fee=0, environment_temperature=25, current_temperature=26.0, power=False, ac_usage_time=0, ac_fee=0),
        Room(room_number='房间二', is_occupied=False, total_fee=0, environment_temperature=25, current_temperature=26.0, power=False, ac_usage_time=0, ac_fee=0),
        Room(room_number='房间三', is_occupied=False, total_fee=0, environment_temperature=25, current_temperature=26.0, power=False, ac_usage_time=0, ac_fee=0),
        Room(room_number='房间四', is_occupied=False, total_fee=0, environment_temperature=25, current_temperature=26.0, power=False, ac_usage_time=0, ac_fee=0),
        Room(room_number='房间五', is_occupied=False, total_fee=0, environment_temperature=25, current_temperature=26.0, power=False, ac_usage_time=0, ac_fee=0),
    ]
    Room.objects.bulk_create(rooms_to_add)

class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_delete_all_data'),  # 调整为你的实际前一个迁移文件
    ]

    operations = [
        migrations.RunPython(add_new_rooms),
    ]
